// SC Coastal Permit Tracker — Configuration
// Update portal URLs here if they change

module.exports = {
  server: {
    port: process.env.PORT || 3000,
    host: process.env.HOST || 'localhost',
  },

  database: {
    path: process.env.DB_PATH || require('path').join(__dirname, 'db', 'permits.db'),
  },

  scraper: {
    defaultDateRangeDays: 30,
    minProjectValue: 0, // Filter in UI; scrape everything
    requestDelayMs: 2000,
    pageTimeoutMs: 60000,
    maxRetries: 3,
    retryBaseDelayMs: 2000,

    puppeteer: {
      headless: 'new',
      ...(process.env.PUPPETEER_EXECUTABLE_PATH ? { executablePath: process.env.PUPPETEER_EXECUTABLE_PATH } : {}),
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--window-size=1920,1080',
      ],
      defaultViewport: { width: 1920, height: 1080 },
    },

    screenshotDir: require('path').join(__dirname, 'screenshots'),

    userAgents: [
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0',
    ],
  },

  // ─── Charleston EnerGov Inspection Search Config ────────────────────────────
  // Portal: https://egcss.charleston-sc.gov/energov_prod/selfservice#/search
  charleston: {
    // PRIMARY search: Framing inspections that passed
    primaryInspectionTypes: [
      'Residential Building Framing',
      'Commercial Building Framing',
      'Truss Framing Inspection',
    ],

    primaryStatuses: [
      'Pass - Global',
      'Passed - Permit',
    ],

    // ALL passed status variants
    allPassedStatuses: [
      'Pass - Global',
      'Passed - Permit',
      'Passed - Plan',
      'Passed - Requests',
      'Passed - Business License',
      'Partial Pass - Global',
      'Partially Passed - Permit',
      'Partially Passed - Plan',
    ],

    // Scheduled/pending statuses (for opportunity scanner)
    scheduledStatuses: [
      'Scheduled - Permit',
      'Requested - Permit',
      'Pending - Permit',
      'Scheduled - Global',
      'Pending - Global',
    ],

    // ── DRYWALL OPPORTUNITY SIGNAL INSPECTION TYPES ──
    signals: {
      high: {
        framing: ['Residential Building Framing', 'Commercial Building Framing', 'Truss Framing Inspection'],
        roughIns: ['Residential Plumbing Rough', 'Residential Electrical Rough', 'Residential Mechanical Rough'],
        insulation: ['Residential Building Insulation', 'Commercial Building Insulation'],
        energyEnvelope: ['Residential Energy Envelope', 'Commercial Energy Envelope'],
        fireRatedWall: ['Residential Fire Rated Wall Assembly', 'Commercial Fire Rated Assembly'],
      },
      medium: {
        sheathing: ['Residential Building Sheathing', 'Commercial Building Sheathing'],
        strapping: ['Residential Building Strapping', 'Commercial Building Strapping'],
        gasRough: ['Residential Gas Rough', 'Commercial Gas Rough'],
        fireplaceFraming: ['Fireplace Framing', 'Fireplace Rough'],
        sprinklerRough: ['Residential Sprinkler Rough'],
        fireAlarmRough: ['Fire Alarm - Rough', 'Fire Alarm - Quick Rough'],
      },
      low: {
        foundation: [
          'Residential Building Foundation', 'Residential Building Slab Inspection',
          'Residential Building Foundation Wall', 'Residential Building Footer',
          'Residential Building Mono-slab', 'Residential Column/Pier Foundation',
        ],
        bondBeam: ['Residential Building Bond Beam', 'Commercial Building Bond Beam'],
        electricalSlab: ['Residential Electrical Slab', 'Commercial Electrical Slab'],
        plumbingSlab: ['Residential Plumbing Slab', 'Commercial Plumbing Slab'],
        electricalUnderground: ['Residential Electrical Underground', 'Commercial Electrical Underground'],
      },
    },

    // Signal tag abbreviations for the UI
    signalTags: {
      'Residential Building Framing': 'FRAME',
      'Commercial Building Framing': 'FRAME',
      'Truss Framing Inspection': 'TRUSS',
      'Residential Electrical Rough': 'ELEC-R',
      'Commercial Electrical Rough': 'ELEC-R',
      'Residential Plumbing Rough': 'PLUMB-R',
      'Commercial Plumbing Rough': 'PLUMB-R',
      'Residential Mechanical Rough': 'MECH-R',
      'Commercial Mechanical Rough': 'MECH-R',
      'Residential Gas Rough': 'GAS-R',
      'Commercial Gas Rough': 'GAS-R',
      'Residential Building Insulation': 'INSULATION',
      'Commercial Building Insulation': 'INSULATION',
      'Residential Energy Envelope': 'ENVELOPE',
      'Commercial Energy Envelope': 'ENVELOPE',
      'Residential Building Sheathing': 'SHEATHING',
      'Commercial Building Sheathing': 'SHEATHING',
      'Residential Building Strapping': 'STRAPPING',
      'Commercial Building Strapping': 'STRAPPING',
      'Residential Fire Rated Wall Assembly': 'FIRE-WALL',
      'Commercial Fire Rated Assembly': 'FIRE-WALL',
      'Fire Alarm - Rough': 'FIRE-ALM-R',
      'Fire Alarm - Quick Rough': 'FIRE-ALM-R',
      'Residential Sprinkler Rough': 'SPRINK-R',
      'Fireplace Framing': 'FP-FRAME',
      'Fireplace Rough': 'FP-FRAME',
      'Residential Building Foundation': 'FOUNDATION',
      'Residential Building Slab Inspection': 'FOUNDATION',
      'Residential Building Foundation Wall': 'FOUNDATION',
      'Residential Building Footer': 'FOUNDATION',
      'Residential Building Mono-slab': 'FOUNDATION',
      'Residential Column/Pier Foundation': 'FOUNDATION',
      'Residential Building Bond Beam': 'BOND-BEAM',
      'Commercial Building Bond Beam': 'BOND-BEAM',
      'Residential Electrical Slab': 'ELEC-SLAB',
      'Residential Plumbing Slab': 'PLUMB-SLAB',
      'Residential Electrical Underground': 'ELEC-UG',
    },

    // ALL inspection types for the deep scanner (complete list)
    allInspectionTypes: [
      'Residential Building Bond Beam', 'Residential Building Final', 'Residential Building Footer',
      'Residential Building Foundation', 'Residential Building Foundation Wall', 'Residential Building Framing',
      'Residential Building Insulation', 'Residential Building Mono-slab', 'Residential Building Sheathing',
      'Residential Building Slab Inspection', 'Residential Building Strapping', 'Residential Column/Pier Foundation',
      'Residential Electrical Bonding', 'Residential Electrical Final', 'Residential Electrical Grounding',
      'Residential Electrical Pre-Power & Service', 'Residential Electrical Rough', 'Residential Electrical Slab',
      'Residential Electrical Temporary Power', 'Residential Electrical T-Pole; Pre-power & Service',
      'Residential Electrical Underground', 'Residential Plumbing Final', 'Residential Plumbing Rough',
      'Residential Plumbing Sewer', 'Residential Plumbing Sewer Lateral', 'Residential Plumbing Shower Pan',
      'Residential Plumbing Slab', 'Residential Plumbing Water Lateral', 'Residential Mechanical Above Ceiling',
      'Residential Mechanical Final', 'Residential Mechanical Rough', 'Residential Mechanical Test & Balance Report',
      'Residential Gas Final', 'Residential Gas Pre-Service', 'Residential Gas Rough', 'Residential Gas Slab',
      'Residential Generator Final', 'Residential Energy Envelope', 'Residential Fire Rated Wall Assembly',
      'Residential Pool Deck Electrical Bonding', 'Residential Sprinkler Final', 'Residential Sprinkler Hydro Test',
      'Residential Sprinkler Rough', 'Commercial Building Above Ceiling', 'Commercial Building Bond Beam',
      'Commercial Building Final', 'Commercial Building Footer', 'Commercial Building Foundation or Slab',
      'Commercial Building Foundation Wall', 'Commercial Building Framing', 'Commercial Building Insulation',
      'Commercial Building Mono-slab', 'Commercial Building Sheathing', 'Commercial Building Slab',
      'Commercial Building Slab Inspection', 'Commercial Building Strapping', 'Commercial Column/Pier Foundation',
      'Truss Framing Inspection', 'Fireplace Framing', 'Fireplace Rough', 'Fireplace Final',
      'Fire Alarm - Final', 'Fire Alarm - Rough', 'Fire Alarm - Quick Final', 'Fire Alarm - Quick Rough',
      'Fire Sprinkler - Final', 'Fire Sprinkler - Hydrostatic', 'Fire Sprinkler - Quick Final', 'Fire Sprinkler - Rough',
      'Certificate of Occupancy Inspection',
    ],
  },

  // ─── Citizenserve Installation IDs ──────────────────────────────────────────
  citizenserve: {
    baseUrl: 'https://www.citizenserve.com/Portal/PortalController',
    installations: {
      isleOfPalms:  { id: 286, name: 'Isle of Palms' },
      kiawah:       { id: 287, name: 'Kiawah Island' },
      seabrook:     { id: 288, name: 'Seabrook Island' },
      summerville:  { id: 301, name: 'Town of Summerville' },
      hardeeville:  { id: 232, name: 'City of Hardeeville' },
    },
  },

  municipalities: {
    // ── Core tier: 0-30 min ──────────────────────────────────────────────────
    charleston: {
      name: 'City of Charleston',
      slug: 'charleston',
      portalUrl: 'https://egcss.charleston-sc.gov/energov_prod/selfservice#/search',
      portalType: 'energov',
      active: true,
      driveTimeMinutes: 20,
    },
    mountPleasant: {
      name: 'Town of Mount Pleasant',
      slug: 'mount-pleasant',
      portalUrl: 'https://mtpleasantsc.gov/permits/',
      portalType: 'oracle-opal',
      active: true,
      driveTimeMinutes: 0,
      notes: 'ViewPoint Cloud discontinued July 2024; now Oracle OPAL',
    },
    sullivansIsland: {
      name: "Sullivan's Island",
      slug: 'sullivans-island',
      portalUrl: 'https://www.sullivansisland.sc.gov',
      portalType: 'bsa-online',
      active: true,
      driveTimeMinutes: 15,
      notes: 'BS&A Online permit portal',
      foia: { type: 'email', email: 'bwelch@sullivansisland.sc.gov' },
    },
    isleOfPalms: {
      name: 'Isle of Palms',
      slug: 'isle-of-palms',
      portalUrl: 'https://www.citizenserve.com/Portal/PortalController?CommunityType=Portal&installationID=286',
      portalType: 'citizenserve',
      citizenserveId: 286,
      active: true,
      driveTimeMinutes: 20,
      foia: { type: 'email', email: 'dkerr@iop.net' },
    },
    northCharleston: {
      name: 'City of North Charleston',
      slug: 'north-charleston',
      portalUrl: 'https://maps.northcharleston.org/CustomerPortal/',
      portalType: 'arcgis',
      active: true,
      driveTimeMinutes: 25,
    },
    charlestonCounty: {
      name: 'Charleston County',
      slug: 'charleston-county',
      portalUrl: 'https://www.charlestoncounty.org/departments/building-inspection-services/',
      portalType: 'county',
      active: true,
      driveTimeMinutes: 20,
      notes: 'Catch-all for smaller municipalities',
    },

    // ── Core tier: 30-60 min ─────────────────────────────────────────────────
    kiawah: {
      name: 'Kiawah Island',
      slug: 'kiawah',
      portalUrl: 'https://www.citizenserve.com/Portal/PortalController?CommunityType=Portal&installationID=287',
      portalType: 'citizenserve',
      citizenserveId: 287,
      active: true,
      driveTimeMinutes: 35,
      foia: { type: 'email', email: 'foia@kiawahisland.gov' },
    },
    seabrook: {
      name: 'Seabrook Island',
      slug: 'seabrook',
      portalUrl: 'https://www.citizenserve.com/Portal/PortalController?CommunityType=Portal&installationID=288',
      portalType: 'citizenserve',
      citizenserveId: 288,
      active: true,
      driveTimeMinutes: 35,
      foia: { type: 'email', email: 'pwiggins@townofseabrookisland.org' },
    },
    follyBeach: {
      name: 'City of Folly Beach',
      slug: 'folly-beach',
      portalUrl: null,
      portalType: 'none',
      active: false,
      driveTimeMinutes: 35,
      notes: 'No online portal — email only',
      foia: { type: 'email', email: 'permits@follybeach.gov' },
    },
    summerville: {
      name: 'Town of Summerville',
      slug: 'summerville',
      portalUrl: 'https://www.citizenserve.com/Portal/PortalController?CommunityType=Portal&installationID=301',
      portalType: 'citizenserve',
      citizenserveId: 301,
      active: true,
      driveTimeMinutes: 35,
    },
    gooseCreek: {
      name: 'City of Goose Creek',
      slug: 'goose-creek',
      portalUrl: 'https://goosecreeksc.portal.opengov.com',
      portalType: 'opengov',
      active: true,
      driveTimeMinutes: 35,
    },
    berkeleyCounty: {
      name: 'Berkeley County',
      slug: 'berkeley-county',
      portalUrl: 'https://build.berkeleycountysc.gov',
      portalType: 'energov',
      active: true,
      driveTimeMinutes: 45,
    },
    moncksCorner: {
      name: 'Town of Moncks Corner',
      slug: 'moncks-corner',
      portalUrl: null,
      portalType: 'communitycore',
      active: false,
      driveTimeMinutes: 50,
      notes: 'Login-walled CommunityCore portal',
      foia: { type: 'email', email: 'info@monckscornersc.gov' },
    },

    // ── Extended tier: 60-90 min ─────────────────────────────────────────────
    dorchesterCounty: {
      name: 'Dorchester County',
      slug: 'dorchester-county',
      portalUrl: 'https://evolvepublic.infovisionsoftware.com/Dorchester/',
      portalType: 'evolve-public',
      active: true,
      driveTimeMinutes: 45,
    },
    bluffton: {
      name: 'Town of Bluffton',
      slug: 'bluffton',
      portalUrl: 'https://townofblufftonsc-energovweb.tylerhost.net/apps/selfservice',
      portalType: 'energov',
      active: true,
      driveTimeMinutes: 75,
    },
    hiltonHead: {
      name: 'Town of Hilton Head Island',
      slug: 'hilton-head',
      portalUrl: 'https://service.hiltonheadislandsc.gov/CitizenAccess/',
      portalType: 'energov',
      active: true,
      driveTimeMinutes: 80,
    },
    hardeeville: {
      name: 'City of Hardeeville',
      slug: 'hardeeville',
      portalUrl: 'https://www.citizenserve.com/Portal/PortalController?CommunityType=Portal&installationID=232',
      portalType: 'citizenserve',
      citizenserveId: 232,
      active: true,
      driveTimeMinutes: 85,
    },
  },

  // ─── Drive-time lookup from 29464 (Mount Pleasant) ─────────────────────────
  // Pre-computed approximate driving minutes for each municipality
  driveTimesFrom29464: {
    'Town of Mount Pleasant': 0,
    "Sullivan's Island": 15,
    'City of Charleston': 20,
    'Isle of Palms': 20,
    'Charleston County': 20,
    'City of North Charleston': 25,
    'Kiawah Island': 35,
    'Seabrook Island': 35,
    'City of Folly Beach': 35,
    'Town of Summerville': 35,
    'City of Goose Creek': 35,
    'Berkeley County': 45,
    'Dorchester County': 45,
    'Town of Moncks Corner': 50,
    'Town of Bluffton': 75,
    'Town of Hilton Head Island': 80,
    'City of Hardeeville': 85,
  },

  // ─── Excluded Builders (production/national builders to auto-filter) ────────
  // Case-insensitive substring match against builder_name and builder_company
  excludedBuilders: [
    // National production builders
    'D.R. Horton',
    'DR Horton',
    'D R Horton',
    'DRB Homes',
    'DRB Group',
    'Lennar',
    'Pulte',
    'PulteGroup',
    'Del Webb',
    'Centex',
    'Beazer',
    'Toll Bros',
    'Toll Brothers',
    'Toll Southeast',
    'Americas Home Place',
    "America's Home Place",
    'K Hovnanian',
    'Eastwood Homes',
    'Stanley Martin',
    'Schumacher Homes',
    'Ashton Woods',
    'David Weekly',
    'David Weekley',
    'John Weiland',
    'Kolter Homes',
    'Starlight Homes',
    'Meritage Homes',
    'Ryan Homes',
    'Mungo',
    'Homes by Dickerson',
    'Dream Finder',
    'DreamFinder',
    // Regional / local production & tract builders
    'Rolina Homes',
    'Great Southern',
    'Crescent Homes',
    'Oakmont Homes',
    'Priester Custom',
    'Blue Horizon',
    'Alka',
    'Dillard Jones',
    'Saussy Burbank',
    'Grantham Homes',
    'Generation Homes',
    'Casco',
    'Saltwater Homes',
    'Rooke',
    'New Leaf',
    'Flynn Custom',
    'JacksonBuilt',
    'Jackson Builders',
    'Hunter Quinn',
    'Carson Homes',
    'Galloway Family',
    'Master Homes',
    'Max Crosby',
    'Palmetto Development',
    'Ravenel Construction',
    'Renaissance South',
    'Trellis Residential',
    'Ragland Homes',
    'Fox Creek Homes',
    'Center Park Homes',
    'Center Park Builder',
    'Barrow Building',
    'J. Meyer Homes',
    'J Meyer Homes',
    'Luxe Builders',
    'Watts Builders',
    'Port City Home',
    'Dan Ryan',
    'Mahshie',
    'CKC Properties',
    'Foster Calvin',
    'Hinmar',
    'Jeffrey Builders',
    'Millsite',
    'Oak Marsh',
  ],

  // FUTURE hooks
  enrichment: { enabled: false, apiUrl: null, apiKey: null },
  scheduling: { enabled: false, cronExpression: '0 6 * * *' },
  alerts: { enabled: false, emailRecipients: [], smsRecipients: [] },
  ghl: { enabled: false, webhookUrl: null, pipelineId: null },
};
